---
title: "m21_rt_data_munging"
author: "Joanna Morris"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loads in original Rt file, removes duplicates, puts target in lowercase, and removes rows and columns with only missing values. `duplicated()` is an R base function that takes vector or data.frame as input and selects rows that are duplicates, by negating the result you will remove all duplicate rows in the R data.frame.

```{r}
library(readr)
df <- read_csv("ALL_rt_allvar.csv", show_col_types = FALSE)
df <- df[!duplicated(df), ]  # removes duplicate rows
df <- mutate(df, target_lower = tolower(target))  # puts all targets in lowercase
df$target <- NULL
df[1] <- NULL

df <- df[,colSums(is.na(df))<nrow(df)]  # remove columns with all NAs
df <- df[rowSums(is.na(df)) != ncol(df), ]  # removes rows with all NAs

write_csv(df,"beh_data/ALL_rt_allvar.csv" )
```

```{r}
library(dplyr)
cw_frq <- read_csv("CW_frq.csv")
cw_frq <- distinct(cw_frq)
write_csv(cw_frq, "CW_frq.csv")


nw_frq <- read_csv("NW_frq.csv")
nw_frq <- distinct(nw_frq)
write_csv(nw_frq, "NW_frq.csv")



```

