---
title: "m21_202303_rt v.2"
author: "Joanna Morris"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,  message=FALSE, comment = "")
```

Loads data files


```{r}
library(readr)
library(dplyr)
cw <- read_csv("words_rt_sv_frq.csv")
nw <- read_csv("nwords_rt_sv_frq.csv")
```


```{r c10}
cols <- c( "famsize", "lang_type")  # recode ind variable columns as factors
cw <- cw |> mutate_at(cols, factor)

cols <- c( "famsize", "lang_type", "complexity")
nw <- nw |> mutate_at(cols, factor)

nw_smpl <- filter(nw, complexity == "Simple")
nw_smpl$complexity <- NULL

nw_cplx <- filter(nw, complexity == "Complex")
nw_cplx$complexity <- NULL

```

Removes  rts for errors (column rt.err) and then imputes missing values with the mean for the dataset (column "rt.err.imp") then creates a new column with inverse RTs

```{r c11}
library(tidyr)
cw <- cw |> mutate(rt.err = response_time * correct)  # convert error rts to 0
cw <- cw |> mutate(rt.err = na_if(rt.err, 0))         # convert 0 rts to NA
cw.mean <- mean(cw$rt.err, na.rm = TRUE)  # get mean rt excluding errors
cw <- cw |> mutate(rt.err.imp = ifelse(is.na(rt.err), 
                                       cw.mean, 
                                       rt.err))  # replace missing values with mean
cw <- cw |> mutate(inv.rt = 1/rt.err.imp)  # creates new column with inverse RTs


nw_smpl <- nw_smpl |> mutate(rt.err = response_time * correct)  # convert error rts to 0
nw_smpl <- nw_smpl |> mutate(rt.err = na_if(rt.err, 0))         # convert 0 rts to NA
nw_smpl.mean <- mean(nw_smpl$rt.err, na.rm = TRUE)  # get mean rt excluding errors
nw_smpl <- nw_smpl |> mutate(rt.err.imp = ifelse(is.na(rt.err),
                                                 nw_smpl.mean,
                                                 rt.err))  # replace missing values with mean
nw_smpl <- nw_smpl |> mutate(inv.rt = 1/rt.err.imp)  # creates new column with inverse RTs

nw_cplx <- nw_cplx |> mutate(rt.err = response_time * correct)  # convert error rts to 0
nw_cplx <- nw_cplx |> mutate(rt.err = na_if(rt.err, 0))         # convert 0 rts to NA
nw_cplx.mean <- mean(nw_cplx$rt.err, na.rm = TRUE)  # get mean rt excluding errors
nw_cplx <- nw_cplx |> mutate(rt.err.imp = ifelse(is.na(rt.err), 
                                                 nw_smpl.mean, 
                                                 rt.err))  # replace missing values with mean
nw_cplx <- nw_cplx |> mutate(inv.rt = 1/rt.err.imp)  # creates new column with inverse RTs
```



Determines how much missing data there is. Creates new dataframe with just the missing data

```{r c12}
cw_missing_data<- filter(cw, is.na(cw$rt.err))
(xtab.missing.data <- xtabs(~famsize+lang_type, data=cw_missing_data))

nw.smpl_missing_data<- filter(nw_smpl, is.na(nw_smpl$rt.err))
(xtab.missing.data <- xtabs(~famsize+lang_type, data=nw.smpl_missing_data))

nw.cplx_missing_data<- filter(nw_cplx, is.na(nw_cplx$rt.err))
(xtab.missing.data <- xtabs(~famsize+lang_type, data=nw.cplx_missing_data))
```



Get condition means

```{r c13}

#Define standard error of the mean function

sem <- function(x) sd(x)/sqrt(length(x))

(cw.cond.means <- cw |> 
   group_by(famsize, lang_type) |> 
   summarise(mean = mean(rt.err.imp), 
             se = sem(rt.err.imp),
             num_stim = n()))


(nw_smpl.cond.means <- nw_smpl |> 
    group_by(famsize, lang_type) |> 
    summarise(mean = mean(rt.err.imp), 
              se = sem(rt.err.imp),
              num_stim = n()))

(nw_cplx.cond.means <- nw_cplx |> 
    group_by(famsize, lang_type) |> 
    summarise(mean = mean(rt.err.imp), 
              se = sem(rt.err.imp),
              num_stim = n()))
```

# LME

### Models

```{r c16}
library(lme4)

# COMPLEX WORDS

cw_null.model = lmer(rt.err.imp ~ 1 + (1|SubjID) + (1|target), 
                     data= cw, REML=FALSE)
summary(cw_null.model)

# Main effects models with random intercepts
cw_main.model = lmer(rt.err.imp ~ lang_type + famsize + (1|SubjID) + (1|target),
                     data= cw, REML=FALSE)
summary(cw_main.model)

# Interaction effects models with random intercepts
cw_inter.model = lmer(rt.err.imp ~ lang_type * famsize + (1|SubjID) + (1|target),
                      data= cw, REML=FALSE)
summary(cw_inter.model)

# SIMPLE NONWORDS

nw.smpl_null.model = lmer(rt.err.imp ~ 1 + (1|SubjID) + (1|target), 
                          data= nw_smpl, 
                          REML=FALSE)
summary(nw.smpl_null.model)

# Main effects models with random intercepts
nw.smpl_main.model = lmer(rt.err.imp ~ lang_type + famsize + (1|SubjID) + (1|target),
                          data= nw_smpl, REML=FALSE)
summary(nw.smpl_main.model)

# Interaction effects models with random intercepts
nw.smpl_inter.model = lmer(rt.err.imp ~ lang_type * famsize + (1|SubjID) + (1|target),
                           data= nw_smpl, REML=FALSE)
summary(nw.smpl_inter.model)

# COMPLEX NONWORDS

nw.cplx_null.model = lmer(rt.err.imp ~ 1 + (1|SubjID) + (1|target),
                          data= nw_cplx, REML=FALSE)
summary(nw.cplx_null.model)

# Main effects models with random intercepts
nw.cplx_main.model = lmer(rt.err.imp ~ lang_type + famsize + (1|SubjID) + (1|target), 
                          data= nw_cplx, REML=FALSE)
summary(nw.cplx_main.model)

# Interaction effects models with random intercepts
nw.cplx_inter.model = lmer(rt.err.imp ~ lang_type * famsize  + (1|SubjID) + (1|target),
                           data= nw_cplx, REML=FALSE)
summary(nw.cplx_inter.model)

```

### Model Comparisons

```{r c17}
anova(cw_null.model,cw_main.model)
anova(cw_main.model,cw_inter.model)

anova(nw.smpl_null.model,nw.smpl_main.model)
anova(nw.smpl_main.model,nw.smpl_inter.model)

anova(nw.cplx_null.model,nw.cplx_main.model)
anova(nw.cplx_main.model,nw.cplx_inter.model)
```

