---
title: "m21_rt"
author: "Joanna Morris"
date: "`r Sys.Date()`"
output: pdf_document
---

\scriptsize

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      error = FALSE,
                      comment = "||",
                      fig.height = 4,
                      fig.width = 4)
options(width = 130)
```

# Setup  {-}

Load libraries
```{r, echo=FALSE}
library(tidyverse)
library(afex)
library(gridExtra)
library(emmeans)
library(effectsize)
library(performance)
```


1. Set `ggplot2` parameters
```{r theme, echo = FALSE}
theme_set(theme_classic() +  
            theme(legend.position = "bottom", 
                  axis.text=element_text(size=10),
                  axis.title=element_text(size=9)))

# Define a custom color palette
my_palette <- c(  "#1F78B4","#E31A1C", "#33A02C")


# Create a function to apply this palette
scale_color_custom <- function() {
  scale_color_manual(values = my_palette)
}

scale_fill_custom <- function() {
  scale_fill_manual(values = my_palette)
}

```

# Load Files  {-}
```{r}
rt_1 <- read_csv("rt_data_chrt1.csv")
rt_2 <- read_csv("rt_data_chrt2.csv")
frq <- read_csv("stimuli_cw_frq.csv")
dmg <- read_csv("demo_lang_vsl_pca.csv")
```


```{r}
rt <- bind_rows(Hampshire = rt_1, 
                Providence =rt_2,
                .id = "location")
rt <- rt |> rename(SubjID = subject_nr)
rt <- rt |> mutate(target = tolower(target))
rt_cor <- rt |> filter(correct == 1)

rt_fill <- rt_cor |> filter(str_detect(targ_type, "^FILL"))
rt_exp <- rt_cor |> filter(!str_detect(targ_type, "^FILL"))
```

Plot RT distributions
```{r}
p1 <- rt_exp |> ggplot(aes(x = SubjID, y = response_time)) +
  geom_boxplot()
p1

p2 <- rt_exp |> ggplot(aes(x = response_time, fill = location, colour =location)) +
  geom_density(alpha = .4) +
  scale_fill_custom() +
  scale_color_custom()
p2
```



Divide into word, non-word and difference wave dataframes
```{r}
rt_exp_cln <- rt_exp |>
  separate(targ_type, into = c("trial_type", "family_size", "complexity"), sep = "_",
           remove = TRUE,
           extra = "drop",
           fill = "right")

rt_words <- rt_exp_cln |> filter(trial_type == "CW") |> select(- complexity)
rt_nwords <- rt_exp_cln |> filter(trial_type == "NW")

# all(rt_words$word_trig == frq$word_trig[match(rt_words$target, frq$target)])  # check that match cols are indeed the same
rt_words_dmg<- left_join(rt_words, dmg, join_by(SubjID))

rt_words_frq <- left_join(rt_words_dmg, frq, join_by(target))|>
  select(-cond_trig.y, -word_trig.y) |>
  rename(cond_trig = cond_trig.x, word_trig = word_trig.x) 

rt_words_1 <- rt_words_frq |> filter(location == "Hampshire") |> select(- location)
rt_words_2 <- rt_words_frq |> filter(location == "Providence") |> select(- location)

str(rt_words_1)

```


Standardize the predictors
```{r}
rt_words_1$Log10BF_std <- as.numeric(scale(rt_words_1$Log10BF, center = TRUE, scale = TRUE))
rt_words_1$FS_std <- as.numeric(scale(rt_words_1$FS, center = TRUE, scale = TRUE))
rt_words_1$Log10WF_std <- as.numeric(scale(rt_words_1$Log10WF, center = TRUE, scale = TRUE))
rt_words_1$Dim.2 <- as.numeric(scale(rt_words_1$Dim.2, center = TRUE, scale = TRUE))

rt_words_2$Log10BF_std <- as.numeric(scale(rt_words_2$Log10BF, center = TRUE, scale = TRUE))
rt_words_2$FS_std <- as.numeric(scale(rt_words_2$FS, center = TRUE, scale = TRUE))
rt_words_2$Log10WF_std <- as.numeric(scale(rt_words_2$Log10WF, center = TRUE, scale = TRUE))
rt_words_2$Dim.2 <- as.numeric(scale(rt_words_2$Dim.2, center = TRUE, scale = TRUE))


cor(rt_words_1$Log10BF_std, rt_words_1$FS_std)
```

Use `complete.cases()` to find which rows had missing data in the model-relevant variables:
```{r}
# Specify only the variables used in the model
model_vars <- c("response_time", "Log10BF_std", "FS_std", "Dim.2","SubjID")

# Identify incomplete rows cohort 1
incomplete_cases_1 <- rt_words_1[!complete.cases(rt_words_1[, model_vars]), ]
rt_words_1_cmpl <- rt_words_1[complete.cases(rt_words_1[, model_vars]), ]
# View them
print(incomplete_cases_1)

```

ANOVA Cohort 1
```{r}
anova_model_1 <- mixed(
  response_time ~ Log10BF_std * FS_std * Dim.2 + (1  | SubjID),
  data = rt_words_1_cmpl,
  method = "KR"
)
anova_model_1
summary(anova_model_1)
```

ANOVA Cohort 2
```{r}
anova_model_2 <- mixed(
  response_time ~ Log10BF_std * FS_std * Dim.2 + (1  | SubjID),
  data = rt_words_2,
  method = "KR"
)
anova_model_2
summary(anova_model_2)
```

```{r}
# Extract effect sizes from your ANOVA model and Compute Marginal and Conditional R²
eta_squared(anova_model_1, partial = TRUE)
r2(anova_model_1)

eta_squared(anova_model_2, partial = TRUE)
r2(anova_model_2)

```