---
title: "M21_202303_aov_rt"
author: "Joanna Morris"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,  message=FALSE, comment = "")
```




Loads data files


```{r}
library(readr)
library(dplyr)
cw <- read_csv("words_rt_sv_frq.csv")
nw <- read_csv("nwords_rt_sv_frq.csv")
```


```{r c10}
cols <- c( "famsize", "lang_type")  # recode ind variable columns as factors
cw <- cw |> mutate_at(cols, factor)

cols <- c( "famsize", "lang_type", "complexity")
nw <- nw |> mutate_at(cols, factor)

nw_smpl <- filter(nw, complexity == "Simple")
nw_smpl$complexity <- NULL

nw_cplx <- filter(nw, complexity == "Complex")
nw_cplx$complexity <- NULL

```

Removes  rts for errors (column rt.err) and then imputes missing values with the mean for the dataset (column "rt.err.imp") then creates a new column with inverse RTs

```{r c11}
library(tidyr)
cw <- cw |> mutate(rt.err = response_time * correct)  # convert error rts to 0
cw <- cw |> mutate(rt.err = na_if(rt.err, 0))         # convert 0 rts to NA
cw.mean <- mean(cw$rt.err, na.rm = TRUE)  # get mean rt excluding errors
cw <- cw |> mutate(rt.err.imp = ifelse(is.na(rt.err), 
                                       cw.mean, 
                                       rt.err))  # replace missing values with mean
cw <- cw |> mutate(inv.rt = 1/rt.err.imp)  # creates new column with inverse RTs


nw_smpl <- nw_smpl |> mutate(rt.err = response_time * correct)  # convert error rts to 0
nw_smpl <- nw_smpl |> mutate(rt.err = na_if(rt.err, 0))         # convert 0 rts to NA
nw_smpl.mean <- mean(nw_smpl$rt.err, na.rm = TRUE)  # get mean rt excluding errors
nw_smpl <- nw_smpl |> mutate(rt.err.imp = ifelse(is.na(rt.err),
                                                 nw_smpl.mean,
                                                 rt.err))  # replace missing values with mean
nw_smpl <- nw_smpl |> mutate(inv.rt = 1/rt.err.imp)  # creates new column with inverse RTs

nw_cplx <- nw_cplx |> mutate(rt.err = response_time * correct)  # convert error rts to 0
nw_cplx <- nw_cplx |> mutate(rt.err = na_if(rt.err, 0))         # convert 0 rts to NA
nw_cplx.mean <- mean(nw_cplx$rt.err, na.rm = TRUE)  # get mean rt excluding errors
nw_cplx <- nw_cplx |> mutate(rt.err.imp = ifelse(is.na(rt.err), 
                                                 nw_smpl.mean, 
                                                 rt.err))  # replace missing values with mean
nw_cplx <- nw_cplx |> mutate(inv.rt = 1/rt.err.imp)  # creates new column with inverse RTs
```



Determines how much missing data there is. Creates new dataframe with just the missing data

```{r c12}
cw_missing_data<- filter(cw, is.na(cw$rt.err))
(xtab.missing.data <- xtabs(~famsize+lang_type, data=cw_missing_data))

nw.smpl_missing_data<- filter(nw_smpl, is.na(nw_smpl$rt.err))
(xtab.missing.data <- xtabs(~famsize+lang_type, data=nw.smpl_missing_data))

nw.cplx_missing_data<- filter(nw_cplx, is.na(nw_cplx$rt.err))
(xtab.missing.data <- xtabs(~famsize+lang_type, data=nw.cplx_missing_data))
```



Get condition means

```{r c13}

#Define standard error of the mean function

sem <- function(x) sd(x)/sqrt(length(x))

(cw.cond.means <- cw |> 
   group_by(famsize, lang_type) |> 
   summarise(mean = mean(rt.err.imp), 
             se = sem(rt.err.imp),
             num_stim = n()))


(nw_smpl.cond.means <- nw_smpl |> 
    group_by(famsize, lang_type) |> 
    summarise(mean = mean(rt.err.imp), 
              se = sem(rt.err.imp),
              num_stim = n()))

(nw_cplx.cond.means <- nw_cplx |> 
    group_by(famsize, lang_type) |> 
    summarise(mean = mean(rt.err.imp), 
              se = sem(rt.err.imp),
              num_stim = n()))
```

Barplots

```{r c14, fig.height=6, fig.width=6, echo=TRUE}
library(gridExtra)
p1 <-  cw.cond.means %>% ggplot(aes(x=lang_type, 
                                    y=mean, 
                                    fill = famsize, 
                                    ymin = mean - se, 
                                    ymax = mean + se)) +
  coord_cartesian(xlim = NULL, 
                  ylim = c(525, 750), 
                  expand = TRUE, 
                  default = FALSE,
                  clip = "on") +
  geom_col(position = "dodge", width = 0.5, color = "black")  +
  ylab("RT in milliseconds")  +  
  xlab("Participant Reading Style")  + 
  ggtitle("Complex Words") +
  scale_fill_manual(values = c("coral2", "deepskyblue4"))+ 
  geom_errorbar(width = .08, position = position_dodge(0.5)) + 
  theme_classic() + 
   geom_text(aes(label = round(mean, digits = 0)),
             colour = "white", 
             size = 3, 
             vjust = 3, 
             position = position_dodge(.5))+
  guides(fill=guide_legend(title="Morphological Family Size"))

p2 <-  nw_smpl.cond.means %>% ggplot(aes(x=lang_type, 
                                         y=mean, 
                                         fill = famsize, 
                                         ymin = mean - se, 
                                         ymax = mean + se)) +
  coord_cartesian(xlim = NULL, ylim = c(525, 750), 
                  expand = TRUE, 
                  default = FALSE,
                  clip = "on") +
  geom_col(position = "dodge", width = .7, color = "black")  +
  xlab(" ")  + 
  ylab("RT in milliseconds")  + 
  ggtitle("Simple NonWords") +
  scale_fill_manual(values = c("coral2", "deepskyblue4"))+ 
  geom_errorbar(width = .08, position = position_dodge(0.5)) + 
  theme_classic() + 
  geom_text(aes(label = round(mean, digits = 0)),
             colour = "white", 
             size = 3, 
             vjust = 4.5,
            position = position_dodge(.7)) +
  guides(fill=guide_legend(title="Morphological Family Size"))

p3 <-  nw_cplx.cond.means %>% ggplot(aes(x=lang_type, 
                                         y=mean, 
                                         fill = famsize, 
                                         ymin = mean - se, 
                                         ymax = mean + se)) +
  coord_cartesian(xlim = NULL, ylim = c(525, 750), 
                  expand = TRUE, 
                  default = FALSE,
                  clip = "on") +
  geom_col(position = "dodge", width = .7, color = "black")  +
  xlab("Participant Reading Style")  + 
  ylab("RT in milliseconds")  + 
  ggtitle("Complex NonWords") +
  scale_fill_manual(values = c("coral2", "deepskyblue4"))+ 
  geom_errorbar(width = .08, position = position_dodge(0.5)) + 
  theme_classic() + 
  geom_text(aes(label = round(mean, digits = 0)),
             colour = "white", 
             size = 3, 
             vjust = 4.5,
            position = position_dodge(.7)) +
  guides(fill=guide_legend(title="Morphological Family Size"))

grid.arrange(p1, p2, p3)
# grid.arrange(p2, p3)
```


```{r}

library(ez)

ezANOVA(data = cw,
        dv = rt.err.imp,
        wid = SubjID,
        within = .(famsize),
        within_full = .(famsize, target),
        between = lang_type,
        type = 3)

ezANOVA(data = nw_cplx,
        dv = rt.err.imp,
        wid = SubjID,
        within = .(famsize),
        within_full = .(famsize, target),
        between = lang_type,
        type = 3)

ezANOVA(data = nw_smpl,
        dv = rt.err.imp,
        wid = SubjID,
        within = .(famsize),
        within_full = .(famsize, target),
        between = lang_type,
        type = 3)


```

