%% Clear memory and the command window
clear;
clc;

%% Load eeglab
[ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab;
ALLERP = buildERPstruct([]);
%% Set up variables holding key values 
    
% Dialog box to get info about script variables 
prompt    = {'Enter name of the grand average file:',...
             'Enter the list of bin numbers to plot:',...
             'Enter data collection location:'};
dlgtitle  =  'Input';
dims      =  [1 70];
definput  =  {'M21_VSL2_GA1_DIFFWAVES_ROI','49:50', 'hc'};
my_input  =  inputdlg(prompt,dlgtitle,dims,definput);

DIR       =  pwd;          % Current folder (where the script should be located)
ga_name  =  my_input{1};   % import filename
bins      =  str2num(my_input{2});
location  =  my_input{3};
if strcmp(location, 'hc')
    channels = [34];
else
    channels = [3 2 29 8 23 24 14 13 19];
end

fname     = [ga_name '.erp'];

%% Load grand average waveform
ERP = pop_loaderp('filename', fname, 'filepath', DIR);
CURRENTERP = CURRENTERP + 1;
ALLERP(CURRENTERP) = ERP;    
erplab redraw;

%% Plot Grand Average Waveform

ERP = pop_ploterps( ERP, [bins], [channels] ,...
                        'Axsize', [0.05 0.08],...
                        'BinNum', 'on', ...
                        'Blc', '-50 50',...
                        'Box', [1 1],...
                        'ChLabel', 'on',...
                        'FontSizeChan', 14,...
                        'FontSizeLeg', 14, ...
                        'FontSizeTicks', 12, ...
                        'LegPos', 'right',...
                        'Linespec', {'b-.', 'c-', 'r-.', 'm-' },...
                        'LineWidth', 3,...
                        'Maximize', 'on',...
                        'Position', [110.875 10.55 106.875 31.95], ...
                        'Style', 'Classic', ...
                        'Tag', 'ERP_figure',...
                        'Transparency', 0,...
                        'xscale', [-100.0 600.0   -100 0:100:600], ...
                        'YDir', 'reverse', ...
                        'yscale', [ -6.0 6.0   -6:1:6 ] );
%                        'AutoYlim', 'on', ...

   erplab redraw;
