---
title: "M21 RT Orthographic Sensitivity"
author: "Joanna Morris"
date: "`r Sys.Date()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---


\scriptsize
# Setup  {-}
```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE, 
                      error = FALSE,
                      comment = "||",
                      fig.height = 4,
                      fig.width = 7)
options(width = 150)
```


Load libraries
```{r, echo=FALSE}
library(tidyverse)
library(ggeffects)
library(lme4)
library(afex)
library(gridExtra)
library(emmeans)
library(effectsize)
library(performance)
library(cowplot)  # for use with `plot_grid(x,x,ncol = x)` function
library(e1071) # for use with `skewness()` function
library(lmerTest)
```


1. Set `ggplot2` parameters

<br>

```{r theme, echo = FALSE}
theme_set(theme_classic() +  
            theme(legend.position = "bottom", 
                  axis.text=element_text(size=8.5),
                  axis.title=element_text(size=9)))

my_theme <- theme(strip.text = element_text(size = 7),
                  axis.text.x = element_text(size = 7),
                  legend.text = element_text(size = 6),
                  legend.title = element_blank())

# Define a custom color palette
my_palette <- c("#A6CEE3",  "#FB9A99")
my_palette_2 <- c( "#1F78B4","#E31A1C" )
my_palette_3 <- c("#A6CEE3","#1F78B4","#FB9A99","#E31A1C")


# Create a function to apply this palette
scale_color_custom <- function() {
  scale_color_manual(values = my_palette_2)
}

scale_fill_custom <- function() {
  scale_fill_manual(values = my_palette_2)
}

# Combine theme and scales
my_style <- list(my_theme,scale_color_custom(),scale_fill_custom())
```

<br>

# Load Files and Format Files  {-}

## Load Files

<br>

```{r}
#DIR <- "csv_files"
df_a <- read_csv("rt_data_hc_A.csv")
df_b <- read_csv( "rt_data_hc_B_fixed.csv")
frq_w <- read_csv("frq_cw.csv")
frq_nw <- read_csv("frq_nw.csv")
dmg <- read_csv("demo_lang_vsl_pca_hc.csv")
```

<br>

## Format Files

<br>

```{r}
# Concatenate datasets
rt <- bind_rows(AB = df_a, 
                BA = df_b,
               .id = "List")
rt_dmg<- right_join(dmg, rt, join_by(SubjID == subject_nr)) |>  # Join Participant Demographic and Lang Data
                    mutate(target = tolower(target)) |>
                    filter(correct == 1)

# Divide into Experimental and Filler Items
rt_fill <- rt_dmg |> filter(str_detect(targ_type, "^FILL"))
rt_exp <- rt_dmg |> filter(!str_detect(targ_type, "^FILL"))

# Define Factors and Conditions
rt_exp_format <- rt_exp |>
  separate(targ_type, into = c("trial_type", "family_size", "complexity"), sep = "_",
           remove = TRUE, extra = "drop", fill = "right") 

# Divide into Words and Nonwords
rt_words <- rt_exp_format |> filter(trial_type == "CW") |> select(- complexity)
rt_nwords <- rt_exp_format |> filter(trial_type == "NW")

# Join Stimulus Frequency Data
rt_words_frq <- left_join(rt_words, frq_w, join_by(target))|>
  select(-cond_trig.y, -word_trig.y) |>
  rename(cond_trig = cond_trig.x, word_trig = word_trig.x)  # remove duplicate columns
rt_nwords_frq <-  left_join(rt_nwords, frq_nw, join_by(target==word)) |>   
  select(-cond_trig.y, -word_trig.y) |>
  rename(cond_trig = cond_trig.x, word_trig = word_trig.x)  

# Rename BF_Split and FS_Split columns
rt_words_frq <- rt_words_frq |> rename(Base_Frequency = BF_Split, Family_Size = FS_Split) # Rename BF_Split and FS_Split columns
rt_nwords_frq <- rt_nwords_frq |> rename(Base_Frequency = BF_Split, Family_Size = FS_Split)

# Recode factor levels
# rt_words_frq <- rt_words_frq |>
#   mutate(Base_Frequency = case_match(Base_Frequency, "Low" ~ "Low BF", "High" ~ "High BF"),
#          Family_Size = case_match(Family_Size, "Small" ~ "Small Family", "Large" ~ "Large Family"))
# rt_nwords_frq <- rt_nwords_frq |> mutate(Base_Frequency = case_match(Base_Frequency, "Low" ~ "Low BF", "High" ~ "High BF"),
#                                          Family_Size = case_match(Family_Size, "Small" ~ "Small Family", "Large" ~ "Large Family"))
# 
# rt_words_frq$Orthographic_Sensitivity[rt_words_frq$Orthographic_Sensitivity == "Low"] <- "Low Sensitivity"
# rt_words_frq$Orthographic_Sensitivity[rt_words_frq$Orthographic_Sensitivity == "High"] <- "High Sensitivity"
```

<br>

# Analyse Data

## Plot RT distributions

<br>

```{r, echo = FALSE, fig.width=7}
# RT boxplot
p1 <- rt_words_frq |> ggplot(aes(x = SubjID, y = response_time)) +
  geom_boxplot(colour = "#1F78B4", fill = "#1F78B4", alpha = .4 )+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Words")
p2 <- rt_nwords_frq |> ggplot(aes(x = SubjID, y = response_time)) +
  geom_boxplot(colour = "#E31A1C", fill = "#E31A1C", alpha = .4)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "Non-words")
plot_grid(p1, p2, ncol = 2, labels = "AUTO")

# RT density plot
p1 <- rt_words_frq |> ggplot(aes(x = response_time)) +
  geom_density(colour = "#1F78B4", fill = "#1F78B4", alpha = .4) +
  labs(title = "Words")
p2 <- rt_nwords_frq |> ggplot(aes(x = response_time)) +
  geom_density(colour = "#E31A1C", fill = "#E31A1C", alpha = .4) +
  labs(title = "Non-words")
plot_grid(p1, p2, ncol = 2, labels = "AUTO")

```

<br>

## Test for Skewness

### Base Frequency

<br>

```{r, echo=FALSE, fig.width=7}
# Raw BF
p1 <- ggplot(rt_words_frq, aes(x = BF)) +
  geom_density(colour = "#B2DF8A", fill = "#B2DF8A", alpha = .4) +
  labs(title = "Distribution of Raw Base Frequency")

# Log10BF
p2 <- ggplot(rt_words_frq, aes(x = Log10BF)) +
  geom_density(colour = "#33A02C", fill = "#33A02C", alpha = .4) +
  labs(title = "Distribution of Log10 Base Frequency")+
  scale_fill_custom() +
  scale_color_custom()

plot_grid(p1, p2, ncol = 2, labels = "AUTO")

library(e1071)
# Skewness values
skewness(rt_words_frq$BF, na.rm = TRUE)
skewness(rt_words_frq$Log10BF, na.rm = TRUE)
```

<br>

### Family Size

<br>

```{r}
# Skewness values

rt_words_frq <- rt_words_frq |> mutate(Log10FS = log10(FS))
skewness(rt_words_frq$FS, na.rm = TRUE)
skewness(rt_words_frq$Log10FS, na.rm = TRUE)

# Raw FS
p1 <- ggplot(rt_words_frq, aes(x = FS)) +
  geom_density(colour = "#B2DF8A", fill = "#B2DF8A", alpha = .4) +
  labs(title = "Distribution of Family Size")
# Log10 FS
p2 <- ggplot(rt_words_frq, aes(x = Log10FS)) +
  geom_density(colour = "#B2DF8A", fill = "#B2DF8A", alpha = .4) +
  labs(title = "Distribution of Log10 Family Size")

plot_grid(p1, p2, ncol = 2, labels = "AUTO")
```
